language: java

jdk: openjdk11

cache:
 directories:
 - "$HOME/.m2/repository"

after_success:
  - mvn clean coveralls:report

# addons:
#   sonarcloud:
#     organization: "stackroute"
#     token:
#       secure: "0.............="

# script:
#   - sonar-scanner
